### ISSUE TITLE
Error building latest release

### ISSUE THREAD

**Issue by MysticRyuujin** [ledgerwatch/turbo-geth#1518]
I got this error trying to make with go1.16

commit: `75ad819cc56f9426ec70e51ccf678a73c94c9e2b`
go version: `go1.16 linux/amd64`

```
Building mdbx
cd ethdb/mdbx/dist/ && make clean && make mdbx-static.o && cat config.h
make[1]: Entering directory '/data/github/turbo-geth/ethdb/mdbx/dist'
rm -rf mdbx_stat mdbx_copy mdbx_dump mdbx_load mdbx_chk mdbx_test @* *.[ao] *.[ls]o *.so *.dSYM *~ tmp.db/* \
	*.gcov *.log *.err src/*.o test/*.o mdbx_example dist \
	config.h src/config.h src/version.c *.tar*
make[1]: Leaving directory '/data/github/turbo-geth/ethdb/mdbx/dist'
make[1]: Entering directory '/data/github/turbo-geth/ethdb/mdbx/dist'
(echo '#define MDBX_BUILD_TIMESTAMP "2021-02-25T08:37:37-0600"' \
&& echo '#define MDBX_BUILD_FLAGS "-std=gnu++2a -O2 -g -Wall -Werror -Wextra -Wpedantic -ffunction-sections -fPIC -fvisibility=hidden -std=gnu11 -pthread -Wno-error=attributes  -Wl,--gc-sections,-z,relro,-O1  -lrt "' \
&& echo '#define MDBX_BUILD_COMPILER "cc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0"' \
&& echo '#define MDBX_BUILD_TARGET "x86_64-linux-gnu"' \
) > config.h
cc -O2 -g -Wall -Werror -Wextra -Wpedantic -ffunction-sections -fPIC -fvisibility=hidden -std=gnu11 -pthread -Wno-error=attributes  -DNDEBUG=1 '-DMDBX_CONFIG_H="config.h"' -ULIBMDBX_EXPORTS -c mdbx.c -o mdbx-static.o
make[1]: Leaving directory '/data/github/turbo-geth/ethdb/mdbx/dist'
#define MDBX_BUILD_TIMESTAMP "2021-02-25T08:37:37-0600"
#define MDBX_BUILD_FLAGS "-std=gnu++2a -O2 -g -Wall -Werror -Wextra -Wpedantic -ffunction-sections -fPIC -fvisibility=hidden -std=gnu11 -pthread -Wno-error=attributes  -Wl,--gc-sections,-z,relro,-O1  -lrt "
#define MDBX_BUILD_COMPILER "cc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0"
#define MDBX_BUILD_TARGET "x86_64-linux-gnu"
env GO111MODULE=on go build -trimpath -o /data/github/turbo-geth/build/bin/tg -tags "mdbx" -ldflags "-X main.gitCommit=75ad819cc56f9426ec70e51ccf678a73c94c9e2b" ./cmd/tg
# runtime
/usr/local/go/src/runtime/mgcsweepbuf.go:87:80: memstats.gc_sys undefined (type mstats has no field or method gc_sys)
/usr/local/go/src/runtime/mgcsweepbuf.go:106:102: memstats.gc_sys undefined (type mstats has no field or method gc_sys)
make: *** [Makefile:38: tg] Error 2
```

**Comment by MysticRyuujin** [comment]
I reverted to `go1.15.8` and got this:
```
Building mdbx
cd ethdb/mdbx/dist/ && make clean && make mdbx-static.o && cat config.h
make[1]: Entering directory '/data/github/turbo-geth/ethdb/mdbx/dist'
rm -rf mdbx_stat mdbx_copy mdbx_dump mdbx_load mdbx_chk mdbx_test @* *.[ao] *.[ls]o *.so *.dSYM *~ tmp.db/* \
	*.gcov *.log *.err src/*.o test/*.o mdbx_example dist \
	config.h src/config.h src/version.c *.tar*
make[1]: Leaving directory '/data/github/turbo-geth/ethdb/mdbx/dist'
make[1]: Entering directory '/data/github/turbo-geth/ethdb/mdbx/dist'
(echo '#define MDBX_BUILD_TIMESTAMP "2021-02-25T08:41:33-0600"' \
&& echo '#define MDBX_BUILD_FLAGS "-std=gnu++2a -O2 -g -Wall -Werror -Wextra -Wpedantic -ffunction-sections -fPIC -fvisibility=hidden -std=gnu11 -pthread -Wno-error=attributes  -Wl,--gc-sections,-z,relro,-O1  -lrt "' \
&& echo '#define MDBX_BUILD_COMPILER "cc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0"' \
&& echo '#define MDBX_BUILD_TARGET "x86_64-linux-gnu"' \
) > config.h
cc -O2 -g -Wall -Werror -Wextra -Wpedantic -ffunction-sections -fPIC -fvisibility=hidden -std=gnu11 -pthread -Wno-error=attributes  -DNDEBUG=1 '-DMDBX_CONFIG_H="config.h"' -ULIBMDBX_EXPORTS -c mdbx.c -o mdbx-static.o
make[1]: Leaving directory '/data/github/turbo-geth/ethdb/mdbx/dist'
#define MDBX_BUILD_TIMESTAMP "2021-02-25T08:41:33-0600"
#define MDBX_BUILD_FLAGS "-std=gnu++2a -O2 -g -Wall -Werror -Wextra -Wpedantic -ffunction-sections -fPIC -fvisibility=hidden -std=gnu11 -pthread -Wno-error=attributes  -Wl,--gc-sections,-z,relro,-O1  -lrt "
#define MDBX_BUILD_COMPILER "cc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0"
#define MDBX_BUILD_TARGET "x86_64-linux-gnu"
env GO111MODULE=on go build -trimpath -o /data/github/turbo-geth/build/bin/tg -tags "mdbx" -ldflags "-X main.gitCommit=75ad819cc56f9426ec70e51ccf678a73c94c9e2b" ./cmd/tg
# runtime
/usr/local/go/src/runtime/mcheckmark.go:37:2: undefined: assertWorldStopped
/usr/local/go/src/runtime/mcheckmark.go:42:18: arena.checkmarks undefined (type *heapArena has no field or method checkmarks)
/usr/local/go/src/runtime/mcheckmark.go:46:82: memstats.gcMiscSys undefined (type mstats has no field or method gcMiscSys)
/usr/local/go/src/runtime/mcheckmark.go:50:9: arena.checkmarks undefined (type *heapArena has no field or method checkmarks)
/usr/local/go/src/runtime/mcheckmark.go:91:61: arena.checkmarks undefined (type *heapArena has no field or method checkmarks)
/usr/local/go/src/runtime/mcheckmark.go:93:17: arena.checkmarks undefined (type *heapArena has no field or method checkmarks)
/usr/local/go/src/runtime/metrics.go:315:2: undefined: heapStatsDelta
/usr/local/go/src/runtime/mgcmark.go:1687:5: useCheckmark redeclared in this block
	previous declaration at /usr/local/go/src/runtime/mcheckmark.go:31:5
make: *** [Makefile:38: tg] Error 2
```

**Comment by AskAlexSharov** [comment]
Try “go clean -cache -modcache” and build again with 1.15.*

**Comment by MysticRyuujin** [comment]
No dice

```
Building mdbx
cd ethdb/mdbx/dist/ && make clean && make mdbx-static.o && cat config.h
make[1]: Entering directory '/data/github/turbo-geth/ethdb/mdbx/dist'
rm -rf mdbx_stat mdbx_copy mdbx_dump mdbx_load mdbx_chk mdbx_test @* *.[ao] *.[ls]o *.so *.dSYM *~ tmp.db/* \
	*.gcov *.log *.err src/*.o test/*.o mdbx_example dist \
	config.h src/config.h src/version.c *.tar*
make[1]: Leaving directory '/data/github/turbo-geth/ethdb/mdbx/dist'
make[1]: Entering directory '/data/github/turbo-geth/ethdb/mdbx/dist'
(echo '#define MDBX_BUILD_TIMESTAMP "2021-02-25T08:58:29-0600"' \
&& echo '#define MDBX_BUILD_FLAGS "-std=gnu++2a -O2 -g -Wall -Werror -Wextra -Wpedantic -ffunction-sections -fPIC -fvisibility=hidden -std=gnu11 -pthread -Wno-error=attributes  -Wl,--gc-sections,-z,relro,-O1  -lrt "' \
&& echo '#define MDBX_BUILD_COMPILER "cc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0"' \
&& echo '#define MDBX_BUILD_TARGET "x86_64-linux-gnu"' \
) > config.h
cc -O2 -g -Wall -Werror -Wextra -Wpedantic -ffunction-sections -fPIC -fvisibility=hidden -std=gnu11 -pthread -Wno-error=attributes  -DNDEBUG=1 '-DMDBX_CONFIG_H="config.h"' -ULIBMDBX_EXPORTS -c mdbx.c -o mdbx-static.o
make[1]: Leaving directory '/data/github/turbo-geth/ethdb/mdbx/dist'
#define MDBX_BUILD_TIMESTAMP "2021-02-25T08:58:29-0600"
#define MDBX_BUILD_FLAGS "-std=gnu++2a -O2 -g -Wall -Werror -Wextra -Wpedantic -ffunction-sections -fPIC -fvisibility=hidden -std=gnu11 -pthread -Wno-error=attributes  -Wl,--gc-sections,-z,relro,-O1  -lrt "
#define MDBX_BUILD_COMPILER "cc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0"
#define MDBX_BUILD_TARGET "x86_64-linux-gnu"
env GO111MODULE=on go build -trimpath -o /data/github/turbo-geth/build/bin/tg -tags "mdbx" -ldflags "-X main.gitCommit=75ad819cc56f9426ec70e51ccf678a73c94c9e2b" ./cmd/tg
go: downloading github.com/urfave/cli v1.22.4
go: downloading github.com/peterh/liner v1.2.0
go: downloading github.com/shirou/gopsutil v2.20.8+incompatible
go: downloading github.com/google/btree v1.0.0
go: downloading github.com/RoaringBitmap/roaring v0.5.6-0.20201124195327-6ec715d630bc
go: downloading github.com/spf13/cobra v1.1.1
go: downloading google.golang.org/protobuf v1.25.0
go: downloading github.com/VictoriaMetrics/fastcache v1.5.7
go: downloading github.com/hashicorp/golang-lru v0.5.4
go: downloading google.golang.org/grpc v1.34.0
go: downloading github.com/deckarep/golang-set v0.0.0-20180603214616-504e848d77ea
go: downloading github.com/gballet/go-libpcsclite v0.0.0-20190607065134-2772fd86a8ff
go: downloading github.com/spf13/pflag v1.0.5
go: downloading github.com/c2h5oh/datasize v0.0.0-20200825124411-48ed595a09d2
go: downloading github.com/JekaMas/notify v0.9.4
go: downloading github.com/golang/snappy v0.0.3-0.20201103224600-674baa8c7fc3
go: downloading github.com/golang/protobuf v1.4.3
go: downloading github.com/ugorji/go v1.1.13
go: downloading github.com/ugorji/go/codec v1.1.13
go: downloading golang.org/x/crypto v0.0.0-20200820211705-5c72a883971a
go: downloading github.com/holiman/uint256 v1.1.1
go: downloading github.com/prometheus/client_golang v1.7.1
go: downloading github.com/petar/GoLLRB v0.0.0-20190514000832-33fb24c13b99
go: downloading github.com/cespare/xxhash v1.1.0
go: downloading github.com/pborman/uuid v1.2.1
go: downloading github.com/edsrzf/mmap-go v1.0.0
go: downloading github.com/huin/goupnp v1.0.0
go: downloading golang.org/x/sys v0.0.0-20200909081042-eff7692f9009
go: downloading golang.org/x/net v0.0.0-20200822124328-c89045814202
go: downloading github.com/cespare/xxhash/v2 v2.1.1
go: downloading github.com/stretchr/testify v1.6.1
go: downloading github.com/rs/cors v1.7.0
go: downloading github.com/mattn/go-isatty v0.0.12
go: downloading github.com/ledgerwatch/lmdb-go v1.17.4
go: downloading github.com/tyler-smith/go-bip39 v1.0.2
go: downloading github.com/gorilla/websocket v1.4.2
go: downloading github.com/beorn7/perks v1.0.1
go: downloading github.com/jackpal/go-nat-pmp v1.0.2
go: downloading google.golang.org/genproto v0.0.0-20200526211855-cb27e3aa2013
go: downloading github.com/mattn/go-colorable v0.1.7
go: downloading github.com/google/uuid v1.1.2
go: downloading github.com/wsddn/go-ecdh v0.0.0-20161211032359-48726bab9208
go: downloading github.com/prometheus/procfs v0.1.3
go: downloading github.com/cpuguy83/go-md2man/v2 v2.0.0
go: downloading github.com/anacrolix/log v0.7.0
go: downloading github.com/prometheus/common v0.10.0
go: downloading golang.org/x/text v0.3.3
go: downloading github.com/aristanetworks/goarista v0.0.0-20200812190859-4cb0e71f3c0e
go: downloading golang.org/x/sync v0.0.0-20200625203802-6e8e738ad208
go: downloading github.com/pmezard/go-difflib v1.0.0
go: downloading golang.org/x/time v0.0.0-20200630173020-3af7569d3a1e
go: downloading github.com/anacrolix/torrent v1.15.2
go: downloading github.com/prometheus/client_model v0.2.0
go: downloading github.com/emicklei/dot v0.11.0
go: downloading github.com/grpc-ecosystem/go-grpc-prometheus v1.2.0
go: downloading github.com/prometheus/tsdb v0.10.0
go: downloading github.com/logrusorgru/aurora v2.0.3+incompatible
go: downloading github.com/ethereum/evmc/v7 v7.3.0
go: downloading github.com/grpc-ecosystem/go-grpc-middleware v1.2.2
go: downloading github.com/mattn/go-runewidth v0.0.7
go: downloading github.com/davecgh/go-spew v1.1.1
go: downloading github.com/go-stack/stack v1.8.0
go: downloading github.com/anacrolix/go-libutp v1.0.2
go: downloading github.com/anacrolix/sync v0.2.0
go: downloading github.com/dustin/go-humanize v1.0.0
go: downloading gopkg.in/yaml.v3 v3.0.0-20200313102051-9f266ea9e77c
go: downloading github.com/anacrolix/missinggo v1.2.1
go: downloading github.com/matttproud/golang_protobuf_extensions v1.0.1
go: downloading github.com/anacrolix/dht v0.0.0-20180412060941-24cbf25b72a4
go: downloading github.com/russross/blackfriday/v2 v2.0.1
go: downloading github.com/anacrolix/mmsg v1.0.0
go: downloading github.com/karalabe/usb v0.0.0-20191104083709-911d15fe12a9
go: downloading github.com/anacrolix/dht/v2 v2.5.1-0.20200317023935-129f05e9b752
go: downloading github.com/anacrolix/missinggo/v2 v2.4.1-0.20200227072623-f02f6484f997
go: downloading github.com/shurcooL/sanitized_anchor_name v1.0.0
go: downloading github.com/bradfitz/iter v0.0.0-20191230175014-e8f45d346db8
go: downloading golang.org/x/xerrors v0.0.0-20200804184101-5ec99f83aff1
go: downloading github.com/anacrolix/multiless v0.0.0-20191223025854-070b7994e841
go: downloading github.com/anacrolix/missinggo/perf v1.0.0
go: downloading github.com/mattn/go-sqlite3 v2.0.2+incompatible
go: downloading github.com/huandu/xstrings v1.3.0
go: downloading github.com/status-im/keycard-go v0.0.0-20200402102358-957c09536969
go: downloading github.com/pkg/errors v0.9.1
go: downloading github.com/anacrolix/stm v0.2.0
go: downloading github.com/willf/bloom v2.0.3+incompatible
go: downloading github.com/benbjohnson/immutable v0.2.0
go: downloading github.com/anacrolix/upnp v0.1.1
go: downloading github.com/ryszard/goskiplist v0.0.0-20150312221310-2dfbae5fcf46
go: downloading github.com/willf/bitset v1.1.10
go: downloading github.com/spaolacci/murmur3 v1.1.0
go: downloading go.etcd.io/bbolt v1.3.4
go: downloading github.com/elliotchance/orderedmap v1.2.0
# runtime
/usr/local/go/src/runtime/mcheckmark.go:37:2: undefined: assertWorldStopped
/usr/local/go/src/runtime/mcheckmark.go:42:18: arena.checkmarks undefined (type *heapArena has no field or method checkmarks)
/usr/local/go/src/runtime/mcheckmark.go:46:82: memstats.gcMiscSys undefined (type mstats has no field or method gcMiscSys)
/usr/local/go/src/runtime/mcheckmark.go:50:9: arena.checkmarks undefined (type *heapArena has no field or method checkmarks)
/usr/local/go/src/runtime/mcheckmark.go:91:61: arena.checkmarks undefined (type *heapArena has no field or method checkmarks)
/usr/local/go/src/runtime/mcheckmark.go:93:17: arena.checkmarks undefined (type *heapArena has no field or method checkmarks)
/usr/local/go/src/runtime/metrics.go:315:2: undefined: heapStatsDelta
/usr/local/go/src/runtime/mgcmark.go:1687:5: useCheckmark redeclared in this block
	previous declaration at /usr/local/go/src/runtime/mcheckmark.go:31:5
make: *** [Makefile:38: tg] Error 2
```

**Comment by erthink** [comment]
Hmm, I don't see any errors related to [MDBX](https://github.com/erthink/libmdbx).
Please clarify if I'm wrong.

**Comment by MysticRyuujin** [comment]
I could have the title wrong, maybe it is a `tg` build error, I just saw that the very first line is "Building mdbx" and I didn't see a subsequent "Building x" line

**Comment by erthink** [comment]
> Yeah, looking at the make file it's not clear to me, but it looks like make on mxdb is complete by the time it errors out?

Yes, it looks much like that.
I filed an issue (to make sure) to make mdbx' build scripts less verbose and to avoid such confusion in the future.

**Comment by MysticRyuujin** [comment]
It seems to have built just fine on another server. I'm not sure what's wrong here.

**Comment by MysticRyuujin** [comment]
Ok I figured it out, it was a conflict from upgrading go1.15 to go1.16 - there were residual files that were not overwritten (or removed) correctly. The fix was to wipe my `/usr/local/go` folder and re-install the go tar.

It's working with both 1.15 and 1.16 now
